# ==============================================================================
# Stage 1 — deps: Install production dependencies only
# ==============================================================================
FROM node:20-alpine AS deps

# libc6-compat is required for some native Node modules on Alpine
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy only the files needed for dependency resolution (maximises layer cache)
COPY package.json package-lock.json ./

# ci = clean install (deterministic, reproducible builds)
RUN npm ci --ignore-scripts && npm cache clean --force

# ==============================================================================
# Stage 2 — builder: Build the Next.js application
# ==============================================================================
FROM node:20-alpine AS builder

WORKDIR /app

# Pull in the deps from the previous stage
COPY --from=deps /app/node_modules ./node_modules

# Copy the rest of the source code
COPY . .

# Disable telemetry during the build
ENV NEXT_TELEMETRY_DISABLED=1

# Build the standalone Next.js application
RUN npm run build

# ==============================================================================
# Stage 3 — runner: Minimal production image
# ==============================================================================
FROM node:20-alpine AS runner

WORKDIR /app

# Production hardening
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create a non-root user and group for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy the public assets (images, robots.txt, favicon, etc.)
COPY --from=builder /app/public ./public

# Create the .next directory and set ownership before copying build output
RUN mkdir .next && chown nextjs:nodejs .next

# Copy the standalone server and its bundled node_modules
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Copy the static assets generated by the build (CSS, JS chunks, etc.)
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Drop privileges — run as non-root
USER nextjs

# The standalone server listens on port 3000 by default
EXPOSE 3000

# Set the hostname to 0.0.0.0 so it binds to all interfaces inside the container
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000

# Start the standalone Node.js server
CMD ["node", "server.js"]
